### PR TITLE
Filter out hidden and extensionless files from watching

### PR DESCRIPTION
**Pull request by vipentti**
Relates to discussion in https://github.com/rust-analyzer/rust-analyzer/issues/869

I'm not sure if this is the appropriate place to do the filtering.

### CODE REVIEW

**Comment by matklad** [comment]
Yeah, I think we probably want to put the logic here to `Root`:

https://github.com/rust-analyzer/ra_vfs/blob/31eec527d8b8f772d85f15829c81d7e6a1be8c60/src/roots.rs#L72-L102

`Root` is effectively a predicate which checks if a particular file belongs to it. The existing `is_excluded` function can't be used here: it purpusfully has access only to RelativePath, and so it can't do a syscall required to figure out if the path is file or directory. I think it's fine to add `is_excluded_dir_entry` alongside the `is_excluded`, which would do IO.

**Comment by vipentti** [comment]
Where should the `is_excluded_dir_entry` be called from ? `Roots::contains` ? Do we have to worry about the `IO` performance or should it not matter since the files are only loaded once and then watched for changes ?

**Comment by vipentti** [comment]
Couldn't we also run the check in `is_excluded` ? 
```rust
fn is_excluded(&self, path: &RelativePath) -> bool {
    ///...

    let full_path = path.to_path(&self.path);

    /// use full_path for checking via metadata
}
```
In the case where we have a file without extension

**Comment by matklad** [comment]
@vipentti oh, right... Yeah, I think that'll work fine. I worry a tiny bit about making syscall there, from performance and purity point of view, but I guess we can always optimize later.

**Comment by bjorn3** [comment]
What about `#[path=".abc.rs"] mod abc;` or `include!("abc.my_funky_ext");`. I believe those will be incorrectly ignored.

**Comment by matklad** [comment]
@bjorn3 this is an intended limitation at the moment. A long term plan would be to allow the user to explicitly whitelist weird files for inclusion.

**Comment by bjorn3** [comment]
Got it.

**Comment by vipentti** [comment]
I think `.abc.rs` should work if `path.extension()` reports its extension as `rs`, we filter only extension-less or hidden files *after* checking if they are rust files
```rust
        match path.extension() {
            Some("rs") => false,
            Some(_) => true,
            // Exclude extension-less and hidden files
            None => is_extensionless_or_hidden_file(&self.path, path),
        }
```

**Pull request merged**
